baseurl = "http://ltcgr.com/"
languageCode = "en-us"
title = "Learn to Code Grand Rapids"
googleAnalytics = ""
paginate = 10
theme ="hyde"

[permalinks]
    post = "/:year/:month/:slug"

[params]
	themeColor = "theme-ltcgr"
	
	author = "Learn to Code Grand Rapids"

    description = "Developing, together."

  # The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = ""

  # To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = ""
	copyright = ""

	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = false
		email = ""
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "learntocodegrandrapids"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
		meetup = "Learn-To-Code-Grand-Rapids"
